let
    Source = SharePoint.Files("https://eqmanserv.sharepoint.com/sites/EMS_FPA", [ApiVersion = 15]),
    #"EMS Fixed Fee Forecast xlsx_https://eqmanserv sharepoint com/sites/EMS_FPA/Shared Documents/Profitability/Data/" = Source{[Name="EMS Fixed Fee Forecast.xlsx",#"Folder Path"="https://eqmanserv.sharepoint.com/sites/EMS_FPA/Shared Documents/Profitability/Data/"]}[Content],
    #"Imported Excel Workbook" = Excel.Workbook(#"EMS Fixed Fee Forecast xlsx_https://eqmanserv sharepoint com/sites/EMS_FPA/Shared Documents/Profitability/Data/"),
    ProjectHARP_Sheet = #"Imported Excel Workbook"{[Item="ProjectHARP",Kind="Sheet"]}[Data],
    #"Removed Top Rows" = Table.Skip(ProjectHARP_Sheet,2),
    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"MSA Reference", type text}, {"Project Code", type text}, {"Billing Schedule item", type text}, {"crbb5_billingmethod", Int64.Type}, {"crbb5_billingmethodname", type text}, {"crbb5_billingstartdate", type datetime}, {"crbb5_billingenddate", type datetime}, {"crbb5_baseannualfee", Int64.Type}, {"crbb5_basecurrency", Int64.Type}, {"crbb5_basecurrencyname", type text}, {"crbb5_indexmonth", Int64.Type}, {"crbb5_currentannualfee", Int64.Type}, {"Entity", type text}, {"Project", type text}, {"Project Type", type text}, {"Monthly Fee", Int64.Type}, {"Supersector", type text}, {"Concession expiry", type datetime}, {"BLANK", type text}, {"Exchange", Int64.Type}, {"GBP Value", Int64.Type}, {"31/01/2025", Int64.Type}, {"28/02/2025", Int64.Type}, {"31/03/2025", Int64.Type}, {"30/04/2025", Int64.Type}, {"31/05/2025", Int64.Type}, {"30/06/2025", Int64.Type}, {"31/07/2025", Int64.Type}, {"31/08/2025", Int64.Type}, {"30/09/2025", Int64.Type}, {"31/10/2025", Int64.Type}, {"30/11/2025", Int64.Type}, {"31/12/2025", Int64.Type}, {"31/01/2026", Int64.Type}, {"28/02/2026", Int64.Type}, {"31/03/2026", Int64.Type}, {"30/04/2026", Int64.Type}, {"31/05/2026", Int64.Type}, {"30/06/2026", Int64.Type}, {"31/07/2026", Int64.Type}, {"31/08/2026", Int64.Type}, {"30/09/2026", Int64.Type}, {"31/10/2026", Int64.Type}, {"30/11/2026", Int64.Type}, {"31/12/2026", Int64.Type}, {"31/01/2027", Int64.Type}, {"28/02/2027", Int64.Type}, {"31/03/2027", Int64.Type}, {"30/04/2027", Int64.Type}, {"31/05/2027", Int64.Type}, {"30/06/2027", Int64.Type}, {"31/07/2027", Int64.Type}, {"31/08/2027", Int64.Type}, {"30/09/2027", Int64.Type}, {"31/10/2027", Int64.Type}, {"30/11/2027", Int64.Type}, {"31/12/2027", Int64.Type}, {"31/01/2028", Int64.Type}, {"29/02/2028", Int64.Type}, {"31/03/2028", Int64.Type}, {"30/04/2028", Int64.Type}, {"31/05/2028", Int64.Type}, {"30/06/2028", Int64.Type}, {"31/07/2028", Int64.Type}, {"31/08/2028", Int64.Type}, {"30/09/2028", Int64.Type}, {"31/10/2028", Int64.Type}, {"30/11/2028", Int64.Type}, {"31/12/2028", Int64.Type}, {"31/01/2029", Int64.Type}, {"28/02/2029", Int64.Type}, {"31/03/2029", Int64.Type}, {"30/04/2029", Int64.Type}, {"31/05/2029", Int64.Type}, {"30/06/2029", Int64.Type}, {"31/07/2029", Int64.Type}, {"31/08/2029", Int64.Type}, {"30/09/2029", Int64.Type}, {"31/10/2029", Int64.Type}, {"30/11/2029", Int64.Type}, {"31/12/2029", Int64.Type}, {"31/01/2030", Int64.Type}, {"28/02/2030", Int64.Type}, {"31/03/2030", Int64.Type}, {"30/04/2030", Int64.Type}, {"31/05/2030", Int64.Type}, {"30/06/2030", Int64.Type}, {"31/07/2030", Int64.Type}, {"31/08/2030", Int64.Type}, {"30/09/2030", Int64.Type}, {"31/10/2030", Int64.Type}, {"30/11/2030", Int64.Type}, {"31/12/2030", Int64.Type}, {"31/01/2031", Int64.Type}, {"28/02/2031", Int64.Type}, {"31/03/2031", Int64.Type}, {"30/04/2031", Int64.Type}, {"31/05/2031", Int64.Type}, {"30/06/2031", Int64.Type}, {"31/07/2031", Int64.Type}, {"31/08/2031", Int64.Type}, {"30/09/2031", Int64.Type}, {"31/10/2031", Int64.Type}, {"30/11/2031", Int64.Type}, {"31/12/2031", Int64.Type}, {"31/01/2032", Int64.Type}, {"29/02/2032", Int64.Type}, {"31/03/2032", Int64.Type}, {"30/04/2032", Int64.Type}, {"31/05/2032", Int64.Type}, {"30/06/2032", Int64.Type}, {"31/07/2032", Int64.Type}, {"31/08/2032", Int64.Type}, {"30/09/2032", Int64.Type}, {"31/10/2032", Int64.Type}, {"30/11/2032", Int64.Type}, {"31/12/2032", Int64.Type}, {"31/01/2033", Int64.Type}, {"28/02/2033", Int64.Type}, {"31/03/2033", Int64.Type}, {"30/04/2033", Int64.Type}, {"31/05/2033", Int64.Type}, {"30/06/2033", Int64.Type}, {"31/07/2033", Int64.Type}, {"31/08/2033", Int64.Type}, {"30/09/2033", Int64.Type}, {"31/10/2033", Int64.Type}, {"30/11/2033", Int64.Type}, {"31/12/2033", Int64.Type}, {"31/01/2034", Int64.Type}, {"28/02/2034", Int64.Type}, {"31/03/2034", Int64.Type}, {"30/04/2034", Int64.Type}, {"31/05/2034", Int64.Type}, {"30/06/2034", Int64.Type}, {"31/07/2034", Int64.Type}, {"31/08/2034", Int64.Type}, {"30/09/2034", Int64.Type}, {"31/10/2034", Int64.Type}, {"30/11/2034", Int64.Type}, {"31/12/2034", Int64.Type}, {"31/01/2035", Int64.Type}, {"28/02/2035", Int64.Type}, {"31/03/2035", Int64.Type}, {"30/04/2035", Int64.Type}, {"31/05/2035", Int64.Type}, {"30/06/2035", Int64.Type}, {"31/07/2035", Int64.Type}, {"31/08/2035", Int64.Type}, {"30/09/2035", Int64.Type}, {"31/10/2035", Int64.Type}, {"30/11/2035", Int64.Type}, {"31/12/2035", Int64.Type}, {"Column154", type any}, {"Column155", type any}})
in
    #"Changed Type"