table _Cost_Subcontractor_Forecast
	lineageTag: a23ade2a-7e40-4008-a3aa-5d53b2d6d3c8

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: de898ff1-e0ed-45b6-aa55-dd6679be72de
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 6776b472-f7a8-4783-a261-24e0c423dba7
			defaultHierarchy: LocalDateTable_3a5b13c1-2158-42f5-b5aa-ceb847bd24e5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Project Code'
		dataType: string
		lineageTag: 4d0546b0-021b-438d-98aa-c7abfa611236
		summarizeBy: none
		sourceColumn: Project Code

		annotation SummarizationSetBy = Automatic

	column TimeWorkReference
		dataType: string
		lineageTag: 937e58da-2d69-4f5d-945c-432ae19ce176
		summarizeBy: none
		sourceColumn: TimeWorkReference

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 713103b2-691e-42a8-8531-04d109fa6f9e
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 7523e187-3203-483b-b94f-93917ad2149d
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column 'Snapshot Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7e8de584-589b-4629-85ea-8fb40ceaac5f
		summarizeBy: none
		sourceColumn: Snapshot Date

		variation Variation
			isDefault
			relationship: 3835378b-d81f-41d4-a7ca-aa29109e135d
			defaultHierarchy: LocalDateTable_aa45896c-b20a-4090-9d36-b7ac5f39f897.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Amount
		dataType: decimal
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: 8670308f-da11-429e-b91c-a3f9409d0b12
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column 'Account Code'
		dataType: int64
		formatString: 0
		lineageTag: 154e7154-350b-4357-a845-e2914766c82c
		summarizeBy: count
		sourceColumn: Account Code

		annotation SummarizationSetBy = Automatic

	partition _Cost_Subcontractor_Forecast = m
		mode: import
		source =
				// =====================================================================
				// _Cost_Subcontractor_Forecast  (helper — load disabled)
				// ---------------------------------------------------------------------
				// Purpose:      Subcontractor cost forecast from the client's
				//               "Subcontractor Fees Forecast" file. Conformed to the
				//               fact_Cost_Live schema.
				// Grain:        One row per (Project Code, Month).
				// Dependencies: stg_SubcontractorForecast  (SharePoint Data folder)
				// Load:         DISABLED.
				// ---------------------------------------------------------------------
				// File layout (CONFIRMED from the delivered file):
				//   - WIDE monthly layout: value columns are month-end dates
				//     (1/31/2026 … 12/31/2026), one column per month.
				//   - The header row is ROW 3 (rows 1-2 are a title + blank). The
				//     stg_SubcontractorForecast staging query MUST skip those rows and
				//     promote row 3 as headers before this helper runs.
				//   - Metadata columns: Netsuite N/C, Project Code, Department, Location.
				//   - `Netsuite N/C` holds the account code (60201) — mapped to Account Code.
				//   - `Project Code` is the join key to dim_Project (BWS-01, HAP-03, …).
				// ---------------------------------------------------------------------
				// TODO:
				//   - Month headers display as US M/d/yyyy (see Revenue OOC helper note).
				//   - All rows seen carry N/C 60201; confirm 60203 never appears here.
				// =====================================================================
				let
				    Source = #"stg_SubcontractorForecast",
				
				    // Step 1 — anchor on the metadata columns; unpivot the month columns
				    NonDateColumns = {"Netsuite N/C", "Project Code", "Department", "Location"},
				    Unpivoted = Table.UnpivotOtherColumns(Source, NonDateColumns, "Forecast Date Text", "Amount"),
				
				    // Step 2 — parse the month-end header (US M/d/yyyy) into a real Date
				    ParsedDate = Table.AddColumn(Unpivoted, "Date",
				        each Date.FromText([#"Forecast Date Text"], [Format="dd/MM/yyyy", Culture="en-US"]),
				        type date),
				    Typed = Table.TransformColumnTypes(ParsedDate, {{"Amount", Currency.Type}}),
				
				    // Step 3 — Account Code from Netsuite N/C, then constants
				    Renamed        = Table.RenameColumns(Typed, {{"Netsuite N/C", "Account Code"}}),
				    AddTWR         = Table.AddColumn(Renamed,        "TimeWorkReference", each null,            type text),
				    AddCategory    = Table.AddColumn(AddTWR,         "Category",          each "Subcontractor", type text),
				    AddType        = Table.AddColumn(AddCategory,    "Type",              each "Forecast",      type text),
				    AddSnapshot    = Table.AddColumn(AddType,        "Snapshot Date",     each null,            type date),
				
				    Final = Table.SelectColumns(AddSnapshot,
				        {"Date", "Project Code", "TimeWorkReference", "Account Code",
				         "Category", "Type", "Snapshot Date", "Amount"}),
				
				    // Keep only months after the cutover date
				    FilteredByCutover = Table.SelectRows(Final,
				        each [Date] > _CutoverDate)
				in
				    FilteredByCutover

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

