table _Cost_Staff_Actuals
	lineageTag: 1ebba816-6aea-4aeb-a2df-1780033102ee

	column 'Project Code'
		dataType: string
		lineageTag: 7b6209be-78cc-4143-805b-3ca6dff1e12e
		summarizeBy: none
		sourceColumn: Project Code

		annotation SummarizationSetBy = Automatic

	column TimeWorkReference
		dataType: string
		lineageTag: b0b39a83-671f-45a7-a098-c65dcb48ec85
		summarizeBy: none
		sourceColumn: TimeWorkReference

		annotation SummarizationSetBy = Automatic

	column 'Account Code'
		dataType: int64
		formatString: 0
		lineageTag: d823577a-e670-46f9-9d74-02fd6b2880b7
		summarizeBy: count
		sourceColumn: Account Code

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 5ef25c0b-6518-4d50-a8c5-3bb070b85d7a
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 8c4f060b-2634-4a8e-8ba4-d1ec53d5f195
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column 'Snapshot Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f3a2d7e1-a0f0-4059-9ba8-c54a52f7aba5
		summarizeBy: none
		sourceColumn: Snapshot Date

		variation Variation
			isDefault
			relationship: 5035374c-6a82-4347-b6e0-9dbca3b93733
			defaultHierarchy: LocalDateTable_b1b4b72c-2f56-4801-98ba-fdc29c271f3e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Amount
		dataType: decimal
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: 31cf0957-2f5a-4184-91c2-61a14ebad857
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 7bf98dbc-8a0e-4204-8898-5e18cfd57404
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column StaffKey
		dataType: string
		lineageTag: 69f930e1-ad9a-405a-9f0d-8e95dfb65f6c
		summarizeBy: none
		sourceColumn: StaffKey

		annotation SummarizationSetBy = Automatic

	partition _Cost_Staff_Actuals = m
		mode: import
		source =
				// =====================================================================
				// _Cost_Staff_Actuals  (helper — load disabled)
				// ---------------------------------------------------------------------
				// Purpose:      Aggregate fact_Timesheet_Live up to the fact_Cost_Live
				//               grain (Date × Project Code × TimeWorkReference).
				// Grain:        One row per (Date, Project Code, TimeWorkReference).
				// Dependencies: fact_Timesheet_Live
				// Load:         DISABLED.
				// ---------------------------------------------------------------------
				// Note: EMS 90 rows ARE included here (Chris said they should still
				// reconcile per employee). They are excluded from contract / sector
				// visuals via measure-level filters, not here.
				// =====================================================================
				let
				    Source = #"fact_Timesheet_Live",
				
				    Grouped = Table.Group(Source,
				        {"Date", "Project Code", "TimeWorkReference"},
				        {{"Amount", each List.Sum([Cost]), Currency.Type}}
				    ),
				
				    AddAccountCode = Table.AddColumn(Grouped,        "Account Code",  each null,     Int64.Type),
				    AddCategory    = Table.AddColumn(AddAccountCode, "Category",      each "Staff",  type text),
				    AddType        = Table.AddColumn(AddCategory,    "Type",          each "Actual", type text),
				    AddSnapshot    = Table.AddColumn(AddType,        "Snapshot Date", each null,     type date),
				
				    Final = Table.SelectColumns(AddSnapshot,
				        {"Date", "Project Code", "TimeWorkReference", "Account Code",
				         "Category", "Type", "Snapshot Date", "Amount"}),
				    #"Added Custom" = Table.AddColumn(Final, "StaffKey", each [TimeWorkReference] & "-" & Text.From(Date.Year([Date])), type text),
				
				    // Keep only months on or before the cutover date
				    FilteredByCutover = Table.SelectRows(#"Added Custom",
				        each [Date] <= DateTime.From(_CutoverDate)),
				    #"Filtered Rows" = Table.SelectRows(FilteredByCutover, each true)
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

