table _Revenue_Actuals
	lineageTag: 341f2481-b894-480c-a395-8e4c7d0c0a3b

	column Type
		dataType: string
		lineageTag: 507e178d-d8cb-4e35-b122-146e75c1e235
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column 'Contract Type'
		dataType: string
		lineageTag: 2e39b0e9-3d7c-44b2-a8b5-b9ff07dd995c
		summarizeBy: none
		sourceColumn: Contract Type

		annotation SummarizationSetBy = Automatic

	column 'Snapshot Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d5950225-f635-4a5f-b157-04c2537bda14
		summarizeBy: none
		sourceColumn: Snapshot Date

		variation Variation
			isDefault
			relationship: 8c210dec-960d-4537-aa99-e47cc0e9a103
			defaultHierarchy: LocalDateTable_7535232a-ed96-412b-8e00-012c9c9cacce.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TransactionLineKey
		dataType: string
		lineageTag: 7fb29222-725d-4a3b-b0df-78103338f45b
		summarizeBy: none
		sourceColumn: TransactionLineKey

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 242ec9bb-c16e-4eb7-a923-70123e32e365
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 39e8df3f-bfbd-4b8c-b4ff-6a915782b4c0
			defaultHierarchy: LocalDateTable_1e33ef91-951d-4b30-a276-d690d4fe60f9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Project Code'
		dataType: string
		lineageTag: fe693cb7-41f6-46f7-b3ca-f43e4d5250b3
		summarizeBy: none
		sourceColumn: Project Code

		annotation SummarizationSetBy = Automatic

	column 'Account Code'
		dataType: int64
		formatString: 0
		lineageTag: d1449a76-1ca4-4413-84fb-60684eaae53b
		summarizeBy: count
		sourceColumn: Account Code

		annotation SummarizationSetBy = Automatic

	column Subsidiary
		dataType: string
		lineageTag: b256b7cc-f450-4a2f-b710-04627c808ec1
		summarizeBy: none
		sourceColumn: Subsidiary

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: double
		lineageTag: 51b6ea58-16c5-4366-bc86-18439f2313c7
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition _Revenue_Actuals = m
		mode: import
		source =
				// =====================================================================
				// _Revenue_Actuals  (helper — load disabled)
				// ---------------------------------------------------------------------
				// Purpose:      Revenue actuals from NetSuite GL, conformed to the
				//               fact_Revenue_Live schema. Filtered to the four revenue
				//               account codes only.
				// Grain:        One row per NetSuite revenue line.
				// Dependencies: stg_FinanceOutput FY26_FY2026
				// Load:         DISABLED — right-click query → untick "Enable load"
				// ---------------------------------------------------------------------
				// Account codes included (confirmed by Chris):
				//   40010, 40011, 40012  →  Contract Type = "In Contract"
				//   40014                →  Contract Type = "Out of Contract"
				//
				// Blank Location: Full Name rule:
				//   Subsidiary ends in "ESS"             →  "Italy"
				//   Subsidiary ends in EMS/BWG/BWS or other → "UK"
				//
				// Unique transaction-line key (corrected): [Transaction: Transaction ID]
				//   & "-" & [Transaction Line ID]  →  e.g. "770163-0", "770163-1".
				//
				// Project Code source (corrected): the FY2026 GL has NO literal Project
				//   Code column. The project is the NetSuite Class; the code lives in
				//   [Class: Class External ID] (e.g. "ASH-01"). Renamed below.
				// =====================================================================
				let
				    Source = #"stg_FinanceOutput FY26_FY2026",
				
				    // Step 1 — keep only revenue rows
				    RevenueOnly = Table.SelectRows(Source, each
				        List.Contains({40010, 40011, 40012, 40014}, [#"Account No."])),
				
				    // Step 2 — default blank Location: Full Name
				    FilledLocation = Table.ReplaceValue(
				        RevenueOnly,
				        each [#"Location: Full Name"],
				        each (
				            if [#"Location: Full Name"] <> null and [#"Location: Full Name"] <> ""
				                then [#"Location: Full Name"]
				            else if Text.EndsWith([#"Subsidiary: Full Name"] ?? "", "ESS")
				                then "Italy"
				            else
				                "UK"
				        ),
				        Replacer.ReplaceValue,
				        {"Location: Full Name"}
				    ),
				
				    // Step 3 — Contract Type from Account Code
				    AddContractType = Table.AddColumn(FilledLocation, "Contract Type",
				        each if [#"Account No."] = 40014 then "Out of Contract" else "In Contract",
				        type text),
				
				    // Step 4 — unique line key (Transaction ID + Transaction Line ID)
				    AddTLK = Table.AddColumn(AddContractType, "TransactionLineKey",
				        each Text.From([#"Transaction: Transaction ID"]) & "-" & Text.From([#"Transaction Line ID"]),
				        type text),
				
				    // Step 5 — constants for the fact schema
				    AddType = Table.AddColumn(AddTLK, "Type", each "Actual", type text),
				    AddSnapshot = Table.AddColumn(AddType, "Snapshot Date", each null, type date),
				
				    // Step 6 — final shape (matches fact_Revenue_Live schema)
				    Renamed = Table.RenameColumns(AddSnapshot, {
				        {"Period End Date",          "Date"},
				        {"Account No.",              "Account Code"},
				        {"Sum of Amount",            "Amount"},
				        {"Subsidiary: Full Name",    "Subsidiary"},
				        {"Class: Class External ID", "Project Code"}   // GL has no literal Project Code; Class External ID holds it
				    }),
				
				    Final = Table.SelectColumns(Renamed,
				        {"Date", "Project Code", "Account Code", "Subsidiary",
				         "Type", "Contract Type", "Snapshot Date", "Amount", "TransactionLineKey"}),
				
				    // Keep only months on or before the cutover date
				    FilteredByCutover = Table.SelectRows(Final,
				        each [Date] <= _CutoverDate),
				    #"Filtered Rows" = Table.SelectRows(FilteredByCutover, each true)
				in
				    #"FilteredByCutover"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

