table _Revenue_Forecast_31Dec2025
	lineageTag: aa9066e7-123e-47fd-8de7-4224ad7c5d30

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 294fb5ff-c1de-4012-8ca1-e1813c90f19e
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 175f20b7-6759-4c2e-bf0a-c0d550ed9503
			defaultHierarchy: LocalDateTable_1e10714c-599c-4a3b-b7b7-cc865e1af553.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Project Code'
		dataType: string
		lineageTag: 44cc1c51-23e0-4b90-b11f-2eccd70a46af
		summarizeBy: none
		sourceColumn: Project Code

		annotation SummarizationSetBy = Automatic

	column 'Account Code'
		dataType: int64
		formatString: 0
		lineageTag: 6e9db56b-2a80-4956-b698-619bdf05380f
		summarizeBy: count
		sourceColumn: Account Code

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: e5a95f04-8fe1-4136-8d58-96899653deec
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column 'Contract Type'
		dataType: string
		lineageTag: 9b380884-e794-489f-a401-3d80c84b5764
		summarizeBy: none
		sourceColumn: Contract Type

		annotation SummarizationSetBy = Automatic

	column 'Snapshot Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f7551a1d-ed2e-4ea4-bb66-8ede665043b9
		summarizeBy: none
		sourceColumn: Snapshot Date

		variation Variation
			isDefault
			relationship: d43ad62a-3da7-49eb-b203-af2be8011065
			defaultHierarchy: LocalDateTable_4e8db392-1c9a-4b36-908c-b4482ced2020.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Amount
		dataType: decimal
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############
		lineageTag: de8cb39c-90ff-4b2f-953a-0f89f31b1516
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column TransactionLineKey
		dataType: string
		lineageTag: 9184ab02-e96b-4a6d-8db8-7bfd5a1ea40e
		summarizeBy: none
		sourceColumn: TransactionLineKey

		annotation SummarizationSetBy = Automatic

	column Subsidiary
		dataType: string
		lineageTag: 8dbc3a88-d784-46e5-b08a-f1b9ad56eef5
		summarizeBy: none
		sourceColumn: Subsidiary

		annotation SummarizationSetBy = Automatic

	partition _Revenue_Forecast_31Dec2025 = m
		mode: import
		source =
				// =====================================================================
				// _Revenue_Forecast_31Dec2025  (helper — load disabled)
				// ---------------------------------------------------------------------
				// Purpose:      In-contract revenue forecast from the 31.12.2025
				//               snapshot sheet, unpivoted from wide → long.
				// Grain:        One row per (Project, Forecast Date).
				// Dependencies: stg_EMS Fixed Fee Forecast_31Dec2025
				// Load:         DISABLED — right-click query → untick "Enable load"
				// ---------------------------------------------------------------------
				// Column names (corrected from the latest data screenshots):
				//   - Project code column is `Project` (e.g. "EEC-01"), NOT "Project Code".
				//   - Subsidiary is `Subsidiary (Project) (Project)` (EMS / ESS).
				//   - The wide forecast columns are date-named headers ("31/01/2026", ...).
				//   - The remaining metadata columns (Item, Billing Method, Base/Current
				//     fees, indexation fields, Billing Start/End Date, etc.) MUST all be
				//     listed as anchors so they are NOT unpivoted. Note Billing Start Date /
				//     Billing End Date / Index Uplift Date are real dates but are metadata,
				//     so they belong in the anchor list, not the forecast-period columns.
				// TODO:
				//   - Verify the default Account Code 40010 is correct (in-contract operational).
				// =====================================================================
				let
				    Source = #"stg_EMS Fixed Fee Forecast_31Dec2025",
				
				    // Step 1 — all NON-forecast-period columns (anchors). Everything else
				    //          (the date-named month columns) gets unpivoted.
				    NonDateColumns = {
				        "Item", "Project", "Project Name (Project) (Project)", "Billing Method",
				        "Base annual fee", "Current Annual Fee", "Currency", "Billing frequency p.a.",
				        "Index Uplift Date", "Index Month", "Index Day of Month",
				        "Subsidiary (Project) (Project)", "Billing Start Date", "Billing End Date",
				        "Billing Reference", "Index this month ?", "Base Index", "Current Index",
				        "Inedxation Basis", "Exchange", "Monthly Fee"
				    },
				
				    // Step 2 — unpivot the wide date columns
				    Unpivoted = Table.UnpivotOtherColumns(Source, NonDateColumns, "Forecast Date Text", "Amount"),
				
				    // Step 3 — parse the "31/01/2026" column name into a real Date
				    ParsedDate = Table.AddColumn(Unpivoted, "Date",
				        each Date.From([#"Forecast Date Text"]),
				        type date),
				
				    Typed = Table.TransformColumnTypes(ParsedDate, {{"Amount", Currency.Type}}),
				
				    // Step 4 — surface Project Code and Subsidiary from the source names
				    Renamed = Table.RenameColumns(Typed, {
				        {"Project",                          "Project Code"},
				        {"Subsidiary (Project) (Project)",   "Subsidiary"}
				    }),
				
				    // Step 5 — constants
				    AddSnapshot       = Table.AddColumn(Renamed,         "Snapshot Date",      each #date(2025, 12, 31), type date),
				    AddType           = Table.AddColumn(AddSnapshot,     "Type",               each "Forecast",          type text),
				    AddContractType   = Table.AddColumn(AddType,         "Contract Type",      each "In Contract",       type text),
				    AddAccountCode    = Table.AddColumn(AddContractType, "Account Code",       each 40010,               Int64.Type),    // TODO: confirm default
				    AddTLK            = Table.AddColumn(AddAccountCode,  "TransactionLineKey", each null,                type text),
				
				    Final = Table.SelectColumns(AddTLK,
				        {"Date", "Project Code", "Account Code", "Subsidiary",
				         "Type", "Contract Type", "Snapshot Date", "Amount", "TransactionLineKey"}),
				
				    // Keep only months after the cutover date
				    FilteredByCutover = Table.SelectRows(Final,
				        each [Date] > _CutoverDate)
				in
				    FilteredByCutover

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

