table fact_Revenue_Live
	lineageTag: 988fad42-e263-4d1b-bf0a-0c88916c9c5d

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c07f6257-2c89-4f30-9bd9-d949f7a3b94d
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Account Code'
		dataType: int64
		formatString: 0
		lineageTag: 84003f24-df75-4cc5-8389-ed65ed63c119
		summarizeBy: none
		sourceColumn: Account Code

		annotation SummarizationSetBy = Automatic

	column Subsidiary
		dataType: string
		lineageTag: 9aec5347-d4e9-44e9-8009-c8be188e7cf1
		summarizeBy: none
		sourceColumn: Subsidiary

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: b297760e-539b-4cb7-8747-9c2b9adcadb8
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column 'Contract Type'
		dataType: string
		lineageTag: 1cc2a03c-3a9f-4f20-ba28-ebde11066bcf
		summarizeBy: none
		sourceColumn: Contract Type

		annotation SummarizationSetBy = Automatic

	column 'Snapshot Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 93c3bd04-0458-4726-875f-3bc44149a1fc
		summarizeBy: none
		sourceColumn: Snapshot Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Amount
		dataType: double
		lineageTag: b44499ab-9bdc-4f8c-871b-c1b05859a9e4
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TransactionLineKey
		dataType: string
		lineageTag: 5d24c4d0-e42f-4be9-984f-439896aab05c
		summarizeBy: none
		sourceColumn: TransactionLineKey

		annotation SummarizationSetBy = Automatic

	column 'Project Code'
		dataType: string
		lineageTag: bfb35bf1-0ef8-4617-80b3-88c04c9e7191
		summarizeBy: none
		sourceColumn: Project Code

		annotation SummarizationSetBy = Automatic

	partition fact_Revenue_Live = m
		mode: import
		source =
				// =====================================================================
				// fact_Revenue_Live
				// ---------------------------------------------------------------------
				// Purpose:      Unified revenue fact — actuals + forecast,
				//               in-contract + out-of-contract — in a single table.
				// Grain:        One row per (Date, Project, Account, Type, Snapshot).
				// Dependencies: _Revenue_Actuals, _Revenue_Forecast_31Dec2025,
				//               _Revenue_Forecast_HARP, _Revenue_Forecast_OOC
				// Load:         enabled.
				// ---------------------------------------------------------------------
				// Each helper conforms to the same column shape, so a Table.Combine
				// produces the final fact. Adding a new revenue source means:
				//   1. Build a new helper query in helpers/ with the same column shape.
				//   2. Reference it in the Table.Combine call below.
				// =====================================================================
				let
				    Combined = Table.Combine({
				        #"_Revenue_Actuals",
				        #"_Revenue_Forecast_31Dec2025",
				        #"_Revenue_Forecast_HARP",
				        #"_Revenue_Forecast_OOC"
				    }),
				    #"Filtered Rows" = Table.SelectRows(Combined, each true)
				in
				    Combined

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

