table 'stg_EMS Fixed Fee Forecast_Contracts1'
	lineageTag: 2561ce0f-15f5-4892-875d-c0767f766202

	column 'MSA Reference'
		dataType: string
		lineageTag: 2d169247-873e-41aa-b7a8-6ce85ce1a77e
		summarizeBy: none
		sourceColumn: MSA Reference

		annotation SummarizationSetBy = Automatic

	column 'Project Code'
		dataType: string
		lineageTag: 7e0cbf84-4dd6-4155-9c86-ffffe3ea0848
		summarizeBy: none
		sourceColumn: Project Code

		annotation SummarizationSetBy = Automatic

	column 'Billing Schedule item'
		dataType: string
		lineageTag: f51682a8-695e-42cb-872c-eb5cf1314efe
		summarizeBy: none
		sourceColumn: Billing Schedule item

		annotation SummarizationSetBy = Automatic

	column crbb5_billingmethod
		dataType: double
		lineageTag: 1cd775fa-88f1-4e3b-b864-c4c4956b22df
		summarizeBy: sum
		sourceColumn: crbb5_billingmethod

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column crbb5_billingmethodname
		dataType: string
		lineageTag: 50e6c496-16e6-404c-b079-3b60a854fc22
		summarizeBy: none
		sourceColumn: crbb5_billingmethodname

		annotation SummarizationSetBy = Automatic

	column crbb5_billingstartdate
		dataType: dateTime
		formatString: General Date
		lineageTag: 1df1503d-4fe6-435b-8e24-cabea73cdbfb
		summarizeBy: none
		sourceColumn: crbb5_billingstartdate

		variation Variation
			isDefault
			relationship: 42a1a791-4945-482a-af5e-91d4f0a1b679
			defaultHierarchy: LocalDateTable_7fba4335-b697-4af2-96da-1e969882501c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crbb5_billingenddate
		dataType: dateTime
		formatString: General Date
		lineageTag: bc6cee03-d30c-4c50-bf82-3f410da4f31c
		summarizeBy: none
		sourceColumn: crbb5_billingenddate

		variation Variation
			isDefault
			relationship: f288510c-5078-439f-9af3-dc1c53b46099
			defaultHierarchy: LocalDateTable_f2e06565-4def-4dd7-869a-9b2306595e31.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crbb5_baseannualfee
		dataType: double
		lineageTag: 6e579963-1bdb-4dda-bd95-ecfbbd759de3
		summarizeBy: sum
		sourceColumn: crbb5_baseannualfee

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column crbb5_basecurrency
		dataType: double
		lineageTag: 6f99ac40-8717-4627-bd7c-7aaf544498e5
		summarizeBy: sum
		sourceColumn: crbb5_basecurrency

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column crbb5_basecurrencyname
		dataType: string
		lineageTag: 4c8e7628-d3a5-4dd1-bd9b-cb1e226773be
		summarizeBy: none
		sourceColumn: crbb5_basecurrencyname

		annotation SummarizationSetBy = Automatic

	column crbb5_indexmonth
		dataType: double
		lineageTag: 86f8ef48-dc49-49d8-8514-239b7fb0431c
		summarizeBy: sum
		sourceColumn: crbb5_indexmonth

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column crbb5_currentannualfee
		dataType: double
		lineageTag: 4ab1d305-3899-4007-9b01-184e70befa03
		summarizeBy: sum
		sourceColumn: crbb5_currentannualfee

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Entity
		dataType: string
		lineageTag: eb5195d6-91a1-49e9-9bad-b97309463241
		summarizeBy: none
		sourceColumn: Entity

		annotation SummarizationSetBy = Automatic

	column Project
		dataType: string
		lineageTag: 77debd7d-dbad-48be-8bbf-e92de05d99c3
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column 'Project Type'
		dataType: string
		lineageTag: f84a38b0-02c2-47ee-86c6-53f3eba4078a
		summarizeBy: none
		sourceColumn: Project Type

		annotation SummarizationSetBy = Automatic

	column 'Monthly Fee'
		dataType: double
		lineageTag: 5e1bd472-a474-44e4-a456-d2cd4acd520c
		summarizeBy: sum
		sourceColumn: Monthly Fee

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Supersector
		dataType: string
		lineageTag: 7044a1ef-8d3e-45b1-88d8-7f480ae094c8
		summarizeBy: none
		sourceColumn: Supersector

		annotation SummarizationSetBy = Automatic

	column 'Concession expiry'
		dataType: dateTime
		formatString: General Date
		lineageTag: 59e82c77-73eb-4ca3-825e-47c4799b3a6b
		summarizeBy: none
		sourceColumn: Concession expiry

		variation Variation
			isDefault
			relationship: 5e7ceb49-d00d-46a4-9872-8e9a7b9c2d1e
			defaultHierarchy: LocalDateTable_24d0df16-1775-4a10-8c84-53cfc12659a1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition 'stg_EMS Fixed Fee Forecast_Contracts1' = m
		mode: import
		source =
				let
				    Source = SharePoint.Files("https://eqmanserv.sharepoint.com/sites/EMS_FPA", [ApiVersion = 15]),
				    #"EMS Fixed Fee Forecast xlsx_https://eqmanserv sharepoint com/sites/EMS_FPA/Shared Documents/Profitability/Data/" = Source{[Name="EMS Fixed Fee Forecast.xlsx",#"Folder Path"="https://eqmanserv.sharepoint.com/sites/EMS_FPA/Shared Documents/Profitability/Data/"]}[Content],
				    #"Imported Excel Workbook" = Excel.Workbook(#"EMS Fixed Fee Forecast xlsx_https://eqmanserv sharepoint com/sites/EMS_FPA/Shared Documents/Profitability/Data/"),
				    #"Filtered Rows" = Table.SelectRows(#"Imported Excel Workbook", each ([Hidden] = false)),
				    Contracts_Table = #"Filtered Rows"{[Item="Contracts",Kind="Table"]}[Data]
				in
				    Contracts_Table

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

